config/routes.rb
Rails.application.routes.draw do
  root to: 'team#index'

  resources :team, only: [:index] do
    post 'fetch', on: :collection
  end
end

app/models/team.rb
Team = Struct.new(:id, :name, :col_f, :col_a) do
  FILENAME = 'football.dat'

  def self.all
    load_data.map do |line|
      cols = line.chomp.split(/\s{2,}/)

      id, name = cols[1].split('. ')

      new(id, name, cols[6], cols[8])
    end
  end

  def self.find(team_id)
    all.detect { |team| team.id == team_id.to_s }
  end

  def to_s
    "#{id}. #{name} #{col_f}-#{col_a}"
  end

  private

  def self.load_data
    load_file.each_line.select { |line| line =~ /^\s+\d/ }
  end

  def self.load_file
    File.open(root_path.join(FILENAME))
  end

  def self.root_path
    Rails.root.join('db')
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/team_controller.rb
class TeamController < ApplicationController
  def index
    @teams = Team.all
  end

  def fetch
    @team = Team.find(params[:team])

    respond_to do |format|
      format.js
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Teams
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    = yield

app/views/team/fetch.js.erb
$('#team-info').html("<%= @team %>");

app/views/team/index.html.haml
%h1 Team Info

= form_tag fetch_team_index_path, remote: true do
  = label_tag 'team', 'Select team'
  = select_tag 'team', options_from_collection_for_select(@teams, 'id', 'name')
  = submit_tag 'Show'

%p#team-info No team is selected